### ISSUE TITLE
您好，中文文档的翻译是否有人认领？我想组织一些人来对 vue-ssr 英文文档进行翻译

### ISSUE THREAD

**Issue by dear-lizhihua** [vuejs/vue-ssr-docs#1] opened 2017-04-27 08:46 UTC
您好，尤大，对您编写 vue-ssr 英文文档表示致敬！
之前 @dingyiming 和我组织一些人翻译了 Vue.js 2 和 vuex 2 的中文文档，之后我们还翻译了 [webpack 2 文档](https://doc.webpack-china.org/)。
对此我们很有兴趣继续翻译您编写的文档，希望能够得到您的支持，谢谢！

**Comment by yyx990803** [comment] 2017-04-27 09:30
欢迎！

**Comment by dear-lizhihua** [comment] 2017-04-27 09:37
OK，可以的话，麻烦建立一个 cn 分支，便于我们进行基于不同分支做文件对比，以及提 pr 到官方仓库 cn 分支。
或者有其他的对比差异的翻译方案也可以考虑。

**Comment by yyx990803** [comment] 2017-04-27 10:58
开好了 👌

**Comment by dear-lizhihua** [comment] 2017-04-27 11:30
好的，谢谢。

**Comment by kazupon** [comment] 2017-04-28 03:52
@yyx990803 @dear-lizhihua 
We started the translation project with GitLocalize. 
See #3 

If you are interested in it, please tell the us. 😉

**Comment by a1029563229** [comment] 2017-05-31 06:24
@dear-lizhihua 
请问中文文档的翻译现在完成了吗..我也想参与一下

**Comment by dear-lizhihua** [comment] 2017-05-31 06:36
@a1029563229 
还差这几节
- [Head 管理](head.md)
- [缓存](caching.md)
- [流式渲染](streaming.md)
- [API 参考](api.md)

可以先 fork [我的仓库](https://github.com/dear-lizhihua/vue-ssr-docs)，然后给我提 pr，我再统一合并到 GitLocalize 里面

**Comment by a1029563229** [comment] 2017-05-31 06:47
@dear-lizhihua 好的，翻译完成后我给你提个pr，现在有翻译好的能给我做个参考吗

**Comment by dear-lizhihua** [comment] 2017-05-31 07:11
@a1029563229 已经完成的翻译都在我的仓库的 cn 分支，我是在 master 分支上建立的 cn 分支，这样 master 有更新时候，可以及时合并更新。

**Comment by a1029563229** [comment] 2017-05-31 07:49
@dear-lizhihua 好的

**Comment by dear-lizhihua** [comment] 2017-06-06 07:33
@yyx990803 
小右，你好，已经全部翻译完成，是直接合并到官方仓库的 cn 分支，还是提交到 [GitLocalize](https://gitlocalize.com/repo/101)后再合并？

**Comment by yyx990803** [comment] 2017-06-06 07:43
@dear-lizhihua 建议提交到 GitLocalize 方便后续更新。

**Comment by yyx990803** [comment] 2017-06-06 07:44
另外感谢翻译，辛苦了 👍

**Comment by dear-lizhihua** [comment] 2017-06-06 09:08
![image](https://cloud.githubusercontent.com/assets/15142680/26821846/7bef9a46-4ada-11e7-8ba0-7deb3069d0c3.png)
好的。
GitLocalize 这东西用起来还是挺麻烦的，必须要把每个``符号换成 GitLocalize 自定义的标签

**Comment by dear-lizhihua** [comment] 2017-06-06 09:50
https://gitlocalize.com/repo/101/zh/en/api.md
小右，以下是使用 GitLocalize 发现的一些展示上问题：
### GitLocalize 对带`<`或`>`无法很好的支持
1. ![image](https://cloud.githubusercontent.com/assets/15142680/26822276/129d3a4c-4adc-11e7-9843-af865bd86217.png)
2. ![image](https://cloud.githubusercontent.com/assets/15142680/26822618/417f4a20-4add-11e7-9f45-220d0f43b43e.png)
3. ![image](https://cloud.githubusercontent.com/assets/15142680/26822892/311cfca8-4ade-11e7-8cbd-504b797ebe3d.png)

### GitLocalize 以及对`<code>`嵌套`<code>`也无法很好的支持
![image](https://cloud.githubusercontent.com/assets/15142680/26822994/8b13dd58-4ade-11e7-85d2-3dc0a9f93e2f.png)

### 单引号显示问题
![image](https://cloud.githubusercontent.com/assets/15142680/26823119/0e65a72c-4adf-11e7-9cf0-44bc948005d8.png)
![image](https://cloud.githubusercontent.com/assets/15142680/26823125/14bf0398-4adf-11e7-8cf1-d2833210c13f.png)

**Comment by chikathreesix** [comment] 2017-06-06 12:49
@dear-lizhihua 谢谢您的报告。我们刚刚修复了错误。请检查 🙇

**Comment by dear-lizhihua** [comment] 2017-06-07 02:16
@chikathreesix 你好，这里还是无法正常显示。
GitLocalize 会把正常的文档中的``符号转为<code></code>，我们在录入文档时候，要把所有的``都手动转写一遍，这样会非常的繁琐。能否直接录入原有文档格式，符号转换的事情不要让录入的人来做。
```
en: Provide a template for the entire page's HTML. The template should contain a comment <code data-md-type="codespan" data-md-index="107"><!--vue-ssr-outlet--></code> which serves as the placeholder for rendered app content.
cn: 为整个页面的 HTML 提供一个模板。此模板应包含注释 <code data-md-type="codespan" data-md-index="107"><!--vue-ssr-outlet--></code>，作为渲染应用程序内容的占位符。
```
![image](https://user-images.githubusercontent.com/15142680/26859366-d40c0a04-4b69-11e7-9f6e-d3831c4933ba.png)

![image](https://user-images.githubusercontent.com/15142680/26859376-e4b631d6-4b69-11e7-8f33-03a7a90bfb1b.png)

**Comment by chikathreesix** [comment] 2017-06-07 05:02
@dear-lizhihua 你好！ 我们现在解决这个问题，打算做这些HTML标签更抽象的格式（例如、{0}{/0})。我们将出货一星期左右。

**Comment by dear-lizhihua** [comment] 2017-06-07 06:10
@chikathreesix nice, thank you!

**Comment by dear-lizhihua** [comment] 2017-06-08 05:00
@chikathreesix find new bug
```
// the right value is 
en: `<div>Hello World</div>`
cn: `<div>访问的 URL 是： {{ url }}</div>`
```
![image](https://user-images.githubusercontent.com/15142680/26912957-51a1a81c-4c4a-11e7-84e3-6d59cd8bed90.png)

**Comment by dear-lizhihua** [comment] 2017-06-08 05:12
hi, @chikathreesix , I want to append the original link to the end of the translated document, but gitlocalize does not have this feature.
![image](https://user-images.githubusercontent.com/15142680/26913138-8cf544c2-4c4b-11e7-9f47-11109a6749f2.png)

**Comment by chikathreesix** [comment] 2017-06-08 17:04
Thank you, @dear-lizhihua. That HTML tag issue will be fixed this week. And for adding an original link to the end, currently we are not supporting adding additional content on a translated file. Let me think about how to deal with it.

**Comment by dear-lizhihua** [comment] 2017-06-09 01:29
@chikathreesix
Thanks gitlocalize team effort and look forward to improvement

**Comment by chikathreesix** [comment] 2017-06-13 05:32
Hi @dear-lizhihua , now all the issues above were fixed except the feature to have an additional content on a translated resource. Let us think that how we can have those contents since it'd be a more structural problem.

**Comment by dear-lizhihua** [comment] 2017-06-13 06:09
@chikathreesix 
Yes, I see your improvement, thank you very much for your efforts. Have a nice day!

**Comment by yyx990803** [comment] 2017-06-13 06:49
@dear-lizhihua 踩坑辛苦了，现在 GitLocalize 上面是最新的进度吗？

**Comment by dear-lizhihua** [comment] 2017-06-13 07:23
翻译是最新的，但是翻译完成的得复制到 gitlocalize 上面，现在手动复制了一半，我尽快抽时间复制吧

**Comment by dear-lizhihua** [comment] 2017-06-13 13:30
@chikathreesix 
Sorry, there should be some line breaks here, and the following should be `2`
![image](https://user-images.githubusercontent.com/15142680/27084561-eb91cd02-507e-11e7-9288-561eb9622568.png)
![image](https://user-images.githubusercontent.com/15142680/27084608-19c2528c-507f-11e7-8b29-d1649f7f21c3.png)

**Comment by dear-lizhihua** [comment] 2017-06-13 14:25
@yyx990803 尤大，已经完成全部复制

**Comment by chikathreesix** [comment] 2017-06-13 14:55
@dear-lizhihua Sorry for the trouble. Let us look into them.

**Comment by yyx990803** [comment] 2017-06-15 05:05
@chikathreesix I tested by merging an auto-created PR for the Chinese translation, but after that the page shows "In Conflict" on GitLocalize:

<img width="1159" alt="screen shot 2017-06-15 at 1 05 05 pm" src="https://user-images.githubusercontent.com/499550/27166136-3663e340-51cb-11e7-9a03-52c70193e08b.png">

Any idea? Does it have to do with how I merged the PR? (merged with "rebase and merge")

**Comment by chikathreesix** [comment] 2017-06-15 06:24
@yyx990803 Hmm, no, it's not an expected result. I have just fixed the conflict for now and am looking into the cause now.

**Comment by chikathreesix** [comment] 2017-06-15 09:14
@yyx990803 I found that this is because Redcarpet, a markdown parser we use in GitLocalize doesn't parse indented elements as GitHub does. We might need to switch to other parser... Let us plan on how to fix this.

**Comment by netputer** [comment] 2017-06-28 03:27
我看翻译进度已经 100% 了，大概什么时候发布呀？

**Comment by dear-lizhihua** [comment] 2017-06-28 05:30
@netputer 才发现我有在 GitLocalize 提 pr 的权限……
@yyx990803 尤大，都合进去了，能否发布？

**Comment by netputer** [comment] 2017-06-28 06:40
已经有啦，棒棒棒～

https://ssr.vuejs.org/zh/

**Comment by yyx990803** [comment] 2017-06-28 06:41
发布了~

**Closed by yyx990803** 2017-06-28 06:41 UTC

**Comment by dear-lizhihua** [comment] 2017-06-28 09:01
@chikathreesix 
here is a bug

**Comment by chikathreesix** [comment] 2017-06-29 06:13
@dear-lizhihua Let me look into this. Thank you!
